name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide details below to help us understand your request.
  
  - type: textarea
    id: feature-description
    attributes:
      label: Feature
      description: Describe the feature you'd like to see
      placeholder: A clear and concise description of the feature
    validations:
      required: true
  
  - type: textarea
    id: expected-action
    attributes:
      label: Expected Action for Feature
      description: What should this feature do? How should it work?
      placeholder: Describe the expected functionality and behavior
    validations:
      required: false
  
  - type: textarea
    id: why
    attributes:
      label: Why
      description: Why is this feature important? What problem does it solve?
      placeholder: Explain the motivation and use case for this feature
    validations:
      required: false
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request
      placeholder: Any additional information that might help
    validations:
      required: false
